steps:
  - name: gcr.io/cloud-builders/git
    entrypoint: bash
    args:
      - -c
      - |
        git submodule update --init

  - name: gcr.io/cloud-builders/docker
    entrypoint: bash
    args:
      - -c
      - |
        docker run -v /workspace:/src -v /workspace/public:/target klakegg/hugo:0.95.0

  - name: gcr.io/cloud-builders/gcloud
    entrypoint: bash
    args:
      - -c
      - |
        gcloud app deploy
